### PR TITLE
Blazar Lease UI

### PR DESCRIPTION
**Pull request by xandroc**
Updated UI allows users to reserve physical host and network on the same lease

### CODE REVIEW

**Comment by diurnalist** [comment]
Why does this template live here, and not in blazar-dashboard? This couples development of blazar-dashboard further with horizon changes.

**Comment by xandroc** [comment]
> Why does this template live here, and not in blazar-dashboard? This couples development of blazar-dashboard further with horizon changes.

Yeah, the blazar-dashboard does lean heavily on Horizon, the original blazar dashboard create lease UI itself is rendered by [templates in Horizon](https://github.com/ChameleonCloud/blazar-dashboard/blob/chameleoncloud/stable/ocata/blazar_dashboard/content/leases/templates/leases/_create.html#L25) although those are very generic and used by Horizon code.  In this case though, since the template is specifically for the blazar-dashboard, we could definitely move it over to blazar, even if we still have dependencies to Horizon, it would be the ones that were there by initial design.

**Comment by diurnalist** [comment]
@xandroc that sounds like a good plan, then we have isolated this changeset to a single repository, which is always nice!

**Comment by diurnalist** [comment]
My understanding is that this code moved to blazar-dashboard.

**Pull request closed without merging**
