### PR TITLE
Hide stats that are irrelevant for CHI

### PR DESCRIPTION
**Pull request by nicktimko**
Starting to remove superfluous columns/graphs. Might try to add the node to the instance table (or in the Actions) to provide some real data. Could even just suck that JSON in and display it.

### CODE REVIEW

**Comment by priteau** [comment]
I don't understand the part of the change where you introduce `usedphrase`. What is the impact on what is displayed?

**Comment by nicktimko** [comment]
It's used here: https://github.com/ChameleonCloud/horizon/pull/2/files#diff-975cf9cec2770c97bcaac5d75bef23f8R10 

Minor fix as previously "Allocated" was the word being used for "used" floating IPs but it wasn't getting used in the template. I renamed it `usedphrase` while I was there to be slightly less obtuse than `text`.

**Comment by priteau** [comment]
I think we should also remove RAM / VCPUs / Disk in openstack_dashboard/dashboards/project/instances/templates/instances/_detail_overview.html

**Comment by priteau** [comment]
I updated your first commit to hide flavor hardware details from the Instance Overview page.

**Pull request merged**
